# Required
remote_theme: "mmistakes/minimal-mistakes"

# Required plugin for the theme
plugins:
  - jekyll-include-cache

# Your site settings
title: Pipeline Engineer
description: A Data Driven Approach to Pipeline Projects

# (optional) Base URL â€” leave blank if this is a user page
baseurl: ""
url: "https://pipelineengineer.github.io"

# Optional defaults (if you want a blog)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
